services:
  - type: web
    name: bounty-radar
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DASHBOARD_PORT
        value: '10000'
      - key: DATABASE_URL
        sync: false
      - key: TG_TOKEN
        sync: false
      - key: TG_CHAT_ID
        sync: false
    numInstances: 1
