services:
  - type: worker
    name: bounty-radar
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: TG_TOKEN
        sync: false
      - key: TG_CHAT_ID
        sync: false
    numInstances: 1
